//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAS.Indicators.Technical.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATAS.Indicators.Technical.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute price.
        /// </summary>
        public static string AbsolutePrice {
            get {
                return ResourceManager.GetString("AbsolutePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration max.
        /// </summary>
        public static string AccelMax {
            get {
                return ResourceManager.GetString("AccelMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration start.
        /// </summary>
        public static string AccelStart {
            get {
                return ResourceManager.GetString("AccelStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration step.
        /// </summary>
        public static string AccelStep {
            get {
                return ResourceManager.GetString("AccelStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated.
        /// </summary>
        public static string Accumulated {
            get {
                return ResourceManager.GetString("Accumulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average directional movement index.
        /// </summary>
        public static string ADX {
            get {
                return ResourceManager.GetString("ADX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert File.
        /// </summary>
        public static string AlertFile {
            get {
                return ResourceManager.GetString("AlertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Period.
        /// </summary>
        public static string AllPeriodtxt {
            get {
                return ResourceManager.GetString("AllPeriodtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximation Alert.
        /// </summary>
        public static string ApproximationAlert {
            get {
                return ResourceManager.GetString("ApproximationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApproximationFilter.
        /// </summary>
        public static string ApproximationFilter {
            get {
                return ResourceManager.GetString("ApproximationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area color.
        /// </summary>
        public static string AreaColor {
            get {
                return ResourceManager.GetString("AreaColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average true range.
        /// </summary>
        public static string ATR {
            get {
                return ResourceManager.GetString("ATR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At start.
        /// </summary>
        public static string AtStart {
            get {
                return ResourceManager.GetString("AtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto filter.
        /// </summary>
        public static string AutoFilter {
            get {
                return ResourceManager.GetString("AutoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Filter Period.
        /// </summary>
        public static string AutoFilterPeriod {
            get {
                return ResourceManager.GetString("AutoFilterPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average period.
        /// </summary>
        public static string AveragePeriod {
            get {
                return ResourceManager.GetString("AveragePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text on axis.
        /// </summary>
        public static string AxisTextColor {
            get {
                return ResourceManager.GetString("AxisTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string BackGround {
            get {
                return ResourceManager.GetString("BackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        public static string Bars {
            get {
                return ResourceManager.GetString("Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars direction.
        /// </summary>
        public static string BarsDirection {
            get {
                return ResourceManager.GetString("BarsDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel width.
        /// </summary>
        public static string BBandsWidth {
            get {
                return ResourceManager.GetString("BBandsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bollinger Bands multiplier factor.
        /// </summary>
        public static string BBMultFactor {
            get {
                return ResourceManager.GetString("BBMultFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bollinger Bands period.
        /// </summary>
        public static string BBPeriod {
            get {
                return ResourceManager.GetString("BBPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearish.
        /// </summary>
        public static string Bearlish {
            get {
                return ResourceManager.GetString("Bearlish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bollinger bands.
        /// </summary>
        public static string BollingerBands {
            get {
                return ResourceManager.GetString("BollingerBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom - Left.
        /// </summary>
        public static string BottomLeft {
            get {
                return ResourceManager.GetString("BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom - Right.
        /// </summary>
        public static string BottomRight {
            get {
                return ResourceManager.GetString("BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullish.
        /// </summary>
        public static string Bullish {
            get {
                return ResourceManager.GetString("Bullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buys.
        /// </summary>
        public static string Buys {
            get {
                return ResourceManager.GetString("Buys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Bar.
        /// </summary>
        public static string ByBar {
            get {
                return ResourceManager.GetString("ByBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        public static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Mode.
        /// </summary>
        public static string CalculationMode {
            get {
                return ResourceManager.GetString("CalculationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candle body height.
        /// </summary>
        public static string CandleBodyHeight {
            get {
                return ResourceManager.GetString("CandleBodyHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candle body height filter.
        /// </summary>
        public static string CandleBodyHeightFilter {
            get {
                return ResourceManager.GetString("CandleBodyHeightFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candle height.
        /// </summary>
        public static string CandleHeight {
            get {
                return ResourceManager.GetString("CandleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candle height filter.
        /// </summary>
        public static string CandleHeightFilter {
            get {
                return ResourceManager.GetString("CandleHeightFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candles.
        /// </summary>
        public static string Candles {
            get {
                return ResourceManager.GetString("Candles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity channel index.
        /// </summary>
        public static string CCI {
            get {
                return ResourceManager.GetString("CCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Level Alert.
        /// </summary>
        public static string ChangingLevelAlert {
            get {
                return ResourceManager.GetString("ChangingLevelAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative.
        /// </summary>
        public static string Cumulative {
            get {
                return ResourceManager.GetString("Cumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current day.
        /// </summary>
        public static string CurrentDay {
            get {
                return ResourceManager.GetString("CurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current month.
        /// </summary>
        public static string CurrentMonth {
            get {
                return ResourceManager.GetString("CurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current week.
        /// </summary>
        public static string CurrentWeek {
            get {
                return ResourceManager.GetString("CurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Period.
        /// </summary>
        public static string DaysPeriod {
            get {
                return ResourceManager.GetString("DaysPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        public static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta сoloring.
        /// </summary>
        public static string DeltaColored {
            get {
                return ResourceManager.GetString("DeltaColored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta type.
        /// </summary>
        public static string DeltaType {
            get {
                return ResourceManager.GetString("DeltaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth of market.
        /// </summary>
        public static string DepthMarket {
            get {
                return ResourceManager.GetString("DepthMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth of market filter.
        /// </summary>
        public static string DepthMarketFilter {
            get {
                return ResourceManager.GetString("DepthMarketFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative directional indicator.
        /// </summary>
        public static string DINeg {
            get {
                return ResourceManager.GetString("DINeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive directional indicator.
        /// </summary>
        public static string DIPos {
            get {
                return ResourceManager.GetString("DIPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction filter.
        /// </summary>
        public static string DirectionFilter {
            get {
                return ResourceManager.GetString("DirectionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisor.
        /// </summary>
        public static string Divisor {
            get {
                return ResourceManager.GetString("Divisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge.
        /// </summary>
        public static string Dodge {
            get {
                return ResourceManager.GetString("Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directional movement index.
        /// </summary>
        public static string DX {
            get {
                return ResourceManager.GetString("DX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency Ratio period.
        /// </summary>
        public static string EfficiencyRatioPeriod {
            get {
                return ResourceManager.GetString("EfficiencyRatioPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponential moving average.
        /// </summary>
        public static string EMA {
            get {
                return ResourceManager.GetString("EMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Dev..
        /// </summary>
        public static string FirstDev {
            get {
                return ResourceManager.GetString("FirstDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First line.
        /// </summary>
        public static string FirstLine {
            get {
                return ResourceManager.GetString("FirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame multiplier.
        /// </summary>
        public static string FrameMultiplier {
            get {
                return ResourceManager.GetString("FrameMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Size.
        /// </summary>
        public static string FrameSize {
            get {
                return ResourceManager.GetString("FrameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heatmap_dark_orange {
            get {
                object obj = ResourceManager.GetObject("heatmap_dark_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heatmap_dark_red {
            get {
                object obj = ResourceManager.GetObject("heatmap_dark_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heatmap_grayscale {
            get {
                object obj = ResourceManager.GetObject("heatmap_grayscale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heatmap_light_red {
            get {
                object obj = ResourceManager.GetObject("heatmap_light_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest.
        /// </summary>
        public static string Highest {
            get {
                return ResourceManager.GetString("Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High/Low.
        /// </summary>
        public static string HighLow {
            get {
                return ResourceManager.GetString("HighLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High session.
        /// </summary>
        public static string HighSession {
            get {
                return ResourceManager.GetString("HighSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        public static string Histogram {
            get {
                return ResourceManager.GetString("Histogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal offset.
        /// </summary>
        public static string HorizontalOffset {
            get {
                return ResourceManager.GetString("HorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        public static string Hourly {
            get {
                return ResourceManager.GetString("Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore wicks.
        /// </summary>
        public static string IgnoreWicks {
            get {
                return ResourceManager.GetString("IgnoreWicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keltner Channel multiplier factor.
        /// </summary>
        public static string KCMultFactor {
            get {
                return ResourceManager.GetString("KCMultFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keltner Channel period.
        /// </summary>
        public static string KCPeriod {
            get {
                return ResourceManager.GetString("KCPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear regression.
        /// </summary>
        public static string LinearReg {
            get {
                return ResourceManager.GetString("LinearReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long period.
        /// </summary>
        public static string LongPeriod {
            get {
                return ResourceManager.GetString("LongPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookback period.
        /// </summary>
        public static string LookBack {
            get {
                return ResourceManager.GetString("LookBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower wick.
        /// </summary>
        public static string LowerWick {
            get {
                return ResourceManager.GetString("LowerWick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest.
        /// </summary>
        public static string Lowest {
            get {
                return ResourceManager.GetString("Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low session.
        /// </summary>
        public static string LowSession {
            get {
                return ResourceManager.GetString("LowSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving average convergence/divergence.
        /// </summary>
        public static string MACD {
            get {
                return ResourceManager.GetString("MACD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum ask.
        /// </summary>
        public static string MaximumAsk {
            get {
                return ResourceManager.GetString("MaximumAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum bid.
        /// </summary>
        public static string MaximumBid {
            get {
                return ResourceManager.GetString("MaximumBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum candle body height.
        /// </summary>
        public static string MaximumCandleBodyHeight {
            get {
                return ResourceManager.GetString("MaximumCandleBodyHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum candle height.
        /// </summary>
        public static string MaximumCandleHeight {
            get {
                return ResourceManager.GetString("MaximumCandleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum delta.
        /// </summary>
        public static string MaximumDelta {
            get {
                return ResourceManager.GetString("MaximumDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum trades.
        /// </summary>
        public static string MaximumTrades {
            get {
                return ResourceManager.GetString("MaximumTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum volume.
        /// </summary>
        public static string MaximumVolume {
            get {
                return ResourceManager.GetString("MaximumVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum volume filter.
        /// </summary>
        public static string MaximumVolumeFilter {
            get {
                return ResourceManager.GetString("MaximumVolumeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean deviation.
        /// </summary>
        public static string MeanDeviation {
            get {
                return ResourceManager.GetString("MeanDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize Mode.
        /// </summary>
        public static string Minimizedmode {
            get {
                return ResourceManager.GetString("Minimizedmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum ask.
        /// </summary>
        public static string MinimumAsk {
            get {
                return ResourceManager.GetString("MinimumAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum bid.
        /// </summary>
        public static string MinimumBid {
            get {
                return ResourceManager.GetString("MinimumBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum candle body height.
        /// </summary>
        public static string MinimumCandleBodyHeight {
            get {
                return ResourceManager.GetString("MinimumCandleBodyHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum candle height.
        /// </summary>
        public static string MinimumCandleHeight {
            get {
                return ResourceManager.GetString("MinimumCandleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum delta.
        /// </summary>
        public static string MinimumDelta {
            get {
                return ResourceManager.GetString("MinimumDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum trades.
        /// </summary>
        public static string MinimumTrades {
            get {
                return ResourceManager.GetString("MinimumTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum volume.
        /// </summary>
        public static string MinimumVolume {
            get {
                return ResourceManager.GetString("MinimumVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momentum.
        /// </summary>
        public static string Momentum {
            get {
                return ResourceManager.GetString("Momentum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier.
        /// </summary>
        public static string Multiplier {
            get {
                return ResourceManager.GetString("Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative delta.
        /// </summary>
        public static string NegativeDelta {
            get {
                return ResourceManager.GetString("NegativeDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset multiplier.
        /// </summary>
        public static string OffsetMultiplier {
            get {
                return ResourceManager.GetString("OffsetMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open session.
        /// </summary>
        public static string OpenSession {
            get {
                return ResourceManager.GetString("OpenSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overbought.
        /// </summary>
        public static string Overbought {
            get {
                return ResourceManager.GetString("Overbought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversold.
        /// </summary>
        public static string Oversold {
            get {
                return ResourceManager.GetString("Oversold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint bars.
        /// </summary>
        public static string PaintBars {
            get {
                return ResourceManager.GetString("PaintBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParabolicSAR.
        /// </summary>
        public static string ParabolicSAR {
            get {
                return ResourceManager.GetString("ParabolicSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot Range.
        /// </summary>
        public static string PivotRange {
            get {
                return ResourceManager.GetString("PivotRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive delta.
        /// </summary>
        public static string PositiveDelta {
            get {
                return ResourceManager.GetString("PositiveDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict.
        /// </summary>
        public static string Predict {
            get {
                return ResourceManager.GetString("Predict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day.
        /// </summary>
        public static string PreviousDay {
            get {
                return ResourceManager.GetString("PreviousDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string PreviousMonth {
            get {
                return ResourceManager.GetString("PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string PreviousWeek {
            get {
                return ResourceManager.GetString("PreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative in %.
        /// </summary>
        public static string RelativeInPerent {
            get {
                return ResourceManager.GetString("RelativeInPerent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render periods.
        /// </summary>
        public static string RenderPeriods {
            get {
                return ResourceManager.GetString("RenderPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative strength index.
        /// </summary>
        public static string RSI {
            get {
                return ResourceManager.GetString("RSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative vigor index.
        /// </summary>
        public static string RVI {
            get {
                return ResourceManager.GetString("RVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Dev..
        /// </summary>
        public static string SecondDev {
            get {
                return ResourceManager.GetString("SecondDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second line.
        /// </summary>
        public static string SecondLine {
            get {
                return ResourceManager.GetString("SecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sells.
        /// </summary>
        public static string Sells {
            get {
                return ResourceManager.GetString("Sells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session delta mode.
        /// </summary>
        public static string SessionDeltaMode {
            get {
                return ResourceManager.GetString("SessionDeltaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short period.
        /// </summary>
        public static string ShortPeriod {
            get {
                return ResourceManager.GetString("ShortPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show instrument.
        /// </summary>
        public static string ShowInstrument {
            get {
                return ResourceManager.GetString("ShowInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show period.
        /// </summary>
        public static string ShowPeriod {
            get {
                return ResourceManager.GetString("ShowPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowVolume.
        /// </summary>
        public static string ShowVolume {
            get {
                return ResourceManager.GetString("ShowVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal period.
        /// </summary>
        public static string SignalPeriod {
            get {
                return ResourceManager.GetString("SignalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow factor.
        /// </summary>
        public static string SlowFactor {
            get {
                return ResourceManager.GetString("SlowFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving average.
        /// </summary>
        public static string SMA {
            get {
                return ResourceManager.GetString("SMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothed moving average.
        /// </summary>
        public static string SMMA {
            get {
                return ResourceManager.GetString("SMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        public static string Smooth {
            get {
                return ResourceManager.GetString("Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation.
        /// </summary>
        public static string StdDev {
            get {
                return ResourceManager.GetString("StdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stochastic.
        /// </summary>
        public static string Stochastic {
            get {
                return ResourceManager.GetString("Stochastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text location.
        /// </summary>
        public static string TextLocation {
            get {
                return ResourceManager.GetString("TextLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text size.
        /// </summary>
        public static string TextSize {
            get {
                return ResourceManager.GetString("TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Dev..
        /// </summary>
        public static string ThirdDev {
            get {
                return ResourceManager.GetString("ThirdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticks.
        /// </summary>
        public static string Ticks {
            get {
                return ResourceManager.GetString("Ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time filter, sec.
        /// </summary>
        public static string TimeFilterSec {
            get {
                return ResourceManager.GetString("TimeFilterSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format.
        /// </summary>
        public static string Timeformat {
            get {
                return ResourceManager.GetString("Timeformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top - Left.
        /// </summary>
        public static string TopLeft {
            get {
                return ResourceManager.GetString("TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top - Right.
        /// </summary>
        public static string TopRight {
            get {
                return ResourceManager.GetString("TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades.
        /// </summary>
        public static string Trades {
            get {
                return ResourceManager.GetString("Trades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades Filter.
        /// </summary>
        public static string TradesFilter {
            get {
                return ResourceManager.GetString("TradesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper wick.
        /// </summary>
        public static string UpperWick {
            get {
                return ResourceManager.GetString("UpperWick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать алерты.
        /// </summary>
        public static string UseAlerts {
            get {
                return ResourceManager.GetString("UseAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use filter.
        /// </summary>
        public static string UseFilter {
            get {
                return ResourceManager.GetString("UseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use scale.
        /// </summary>
        public static string UseScale {
            get {
                return ResourceManager.GetString("UseScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TrueRange (KC).
        /// </summary>
        public static string UseTrueRangeKc {
            get {
                return ResourceManager.GetString("UseTrueRangeKc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical offset.
        /// </summary>
        public static string VerticalOffset {
            get {
                return ResourceManager.GetString("VerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        public static string Visualization {
            get {
                return ResourceManager.GetString("Visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string VisualMode {
            get {
                return ResourceManager.GetString("VisualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume filter.
        /// </summary>
        public static string VolumeFilter {
            get {
                return ResourceManager.GetString("VolumeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Visualization Type.
        /// </summary>
        public static string VolumeVisualizationType {
            get {
                return ResourceManager.GetString("VolumeVisualizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave period.
        /// </summary>
        public static string WavePeriod {
            get {
                return ResourceManager.GetString("WavePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted moving average.
        /// </summary>
        public static string WMA {
            get {
                return ResourceManager.GetString("WMA", resourceCulture);
            }
        }
    }
}
